include: images/apko.yaml

contents:
  packages:
    - aws-cli
    - bash
    - busybox
    - ca-certificates-bundle
    - coreutils
    - curl
    - glibc-locale-posix
    - wget
    - wolfi-baselayout

entrypoint:
  command: /usr/bin/aws

annotations:
  org.opencontainers.image.title: 'aws-cli'
  org.opencontainers.image.description: 'aws-cli image based on Wolfi OS'
  org.opencontainers.image.source: 'https://github.com/opopops/wolfi/tree/main/images/aws-cli'
