include: images/apko.yaml

contents:
  packages:
    - bash
    - busybox
    - curl
    - ca-certificates-bundle
    - coreutils
    - glibc-locale-posix
    - jq
    - mc
    - mc-bitnami-2025-compat
    - ncurses
    - readline
    - wolfi-baselayout

entrypoint:
  command: /opt/bitnami/scripts/minio-client/entrypoint.sh

cmd: /opt/bitnami/scripts/minio-client/run.sh

environment:
  BITNAMI_APP_NAME: minio

annotations:
  org.opencontainers.image.title: 'minio-bitnami-client'
  org.opencontainers.image.description: 'MinIO-Bitnami client image based on Wolfi OS'
  org.opencontainers.image.source": 'https://github.com/opopops/wolfi/tree/main/images/minio-bitnami-client'
