include: images/apko.yaml

contents:
  packages:
    - ca-certificates-bundle
    - glibc-locale-posix
    - nginx
    - nginx-package-config
    - nginx-mod-stream
    - wolfi-baselayout

entrypoint:
  command: /usr/sbin/nginx

cmd: -c /etc/nginx/nginx.conf -e /dev/stderr -g daemon off;

stop-signal: SIGQUIT

annotations:
  org.opencontainers.image.title: 'nginx'
  org.opencontainers.image.description: 'Nginx image based on Wolfi OS'
  org.opencontainers.image.source": 'https://github.com/opopops/wolfi/tree/main/images/nginx'
