include: images/apko.yaml

contents:
  packages:
    - ca-certificates-bundle
    - glibc-locale-posix
    - nginx
    - nginx-package-config
    - nginx-mod-stream
    - wolfi-baselayout

accounts:
  groups:
    - groupname: nginx
      gid: 65532
  users:
    - username: nginx
      uid: 65532
      gid: 65532
  run-as: nginx

paths:
  - path: /var/lib/nginx
    type: directory
    permissions: 0o755
    uid: 65532
    gid: 65532
  - path: /var/lib/nginx/html
    type: directory
    permissions: 0o755
    uid: 65532
    gid: 65532
  - path: /var/lib/nginx/logs
    type: directory
    permissions: 0o755
    uid: 65532
    gid: 65532
  - path: /var/lib/nginx/tmp
    type: directory
    permissions: 0o777
    uid: 65532
    gid: 65532
  - path: /var/run
    type: directory
    permissions: 0o777
    uid: 65532
    gid: 65532
  - path: /run/nginx
    type: directory
    permissions: 0o777
    uid: 65532
    gid: 65532

work-dir: /home/nginx

entrypoint:
  command: /usr/sbin/nginx

cmd: -c /etc/nginx/nginx.conf -e /dev/stderr -g 'daemon off;'

stop-signal: SIGQUIT

annotations:
  org.opencontainers.image.title: 'nginx'
  org.opencontainers.image.description: 'Nginx image based on Wolfi OS'
  org.opencontainers.image.source: 'https://github.com/opopops/wolfi/tree/main/images/nginx'
