include: images/apko.yaml

contents:
  packages:
    - ca-certificates-bundle
    - glibc-locale-posix
    - prometheus
    - wolfi-baselayout

entrypoint:
  command: prometheus

annotations:
  org.opencontainers.image.title: 'prometheus'
  org.opencontainers.image.description: 'prometheus image based on Wolfi OS'
  org.opencontainers.image.source": 'https://github.com/opopops/wolfi/tree/main/images/prometheus'
