include: images/apko.yaml

contents:
  packages:
    - aws-cli-v2
    - bash
    - busybox
    - ca-certificates-bundle
    - cosign
    - crane
    - curl
    - docker-cli
    - docker-cli-buildx
    - docker-compose
    - gettext
    - git
    - grype
    - helm
    - helm-docs
    - jq
    - k9s
    - kubectl
    - openssl
    - opentofu
    - py3-ansible-core
    - terragrunt
    - wolfi-baselayout
    - yq

cmd: /usr/bin/sh -l

annotations:
  org.opencontainers.image.title: 'infra-tools'
  org.opencontainers.image.description: 'infra-tools image based on Wolfi OS'
  org.opencontainers.image.source": 'https://github.com/opopops/wolfi/tree/main/images/infra-tools'
