include: images/apko.yaml

contents:
  packages:
    - bash
    - bind-tools
    - busybox
    - ca-certificates-bundle
    - curl
    - dockerize
    - e2fsprogs
    - gettext
    - glibc-locale-posix
    - jq
    - netcat-openbsd
    - util-linux-misc
    - wget
    - wolfi-baselayout
    - yq

entrypoint:
  command: /usr/bin/bash -c

annotations:
  org.opencontainers.image.title: 'shell'
  org.opencontainers.image.description: 'Shell image based on Wolfi OS'
  org.opencontainers.image.source: 'https://github.com/opopops/wolfi/tree/main/images/shell'
