include: images/apko.yaml

contents:
  packages:
    - bash
    - busybox
    - ca-certificates-bundle
    - curl
    - glibc-locale-posix
    - wget
    - wolfi-baselayout

entrypoint:
  command: /usr/bin/bash -c

annotations:
  org.opencontainers.image.title: 'bash'
  org.opencontainers.image.description: 'Bash image based on Wolfi OS'
  org.opencontainers.image.source: 'https://github.com/opopops/wolfi/tree/main/images/bash'
