name: minio-bitnami-client

on:
  schedule:
    - cron: "00 01 * * 1"
  push:
    branches:
      - 'main'
    paths:
      - 'images/minio-bitnami-client/*.yaml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write
  actions: read

jobs:
  publish:
    strategy:
      matrix:
        # https://images.chainguard.dev/directory/image/minio-bitnami-client/versions
        version: [latest, "0.20250312"]
        include:
          - version: latest
            packages: ''
          - version: "0.20250312"
            packages: 'mc-bitnami-2025-compat~0.20250312,mc~0.20250312'
    name: ${{ matrix.version }}
    uses: './.github/workflows/release.yaml'
    with:
      tag: ${{ matrix.version }}
      target: prod
      packages: ${{ matrix.packages }}
    secrets: inherit
