name: minio-bitnami

on:
  schedule:
    - cron: "00 01 * * 1"
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/minio-bitnami.yaml
      - 'images/minio-bitnami/*.yaml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write
  actions: read

jobs:
  publish:
    strategy:
      matrix:
        # https://images.chainguard.dev/directory/image/minio-bitnami/versions
        version: [latest, "0.20250408"]
    name: ${{ matrix.version }}
    uses: './.github/workflows/release.yaml'
    with:
      tag: ${{ matrix.version }}
      target: prod
      packages: >-
        ${{ matrix.version != 'latest' && format('minio-bitnami-2025-compat~{0},minio~{0},mc~{0}', matrix.version) || '' }}
    secrets: inherit
