name: minio-bitnami

on:
  schedule:
    - cron: "00 01 * * 1"
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/minio-bitnami.yaml
      - 'images/minio-bitnami/*.yaml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write
  actions: read

jobs:
  publish:
    strategy:
      matrix:
        # https://images.chainguard.dev/directory/image/minio-bitnami/versions
        version: [latest, "0.20250408"]
        include:
          - version: latest
            packages: ''
          - version: "0.20250408"
            packages: 'minio-bitnami-2025-compat~0.20250408,minio~0.20250408,mc~0.20250408'
    name: ${{ matrix.version }}
    uses: './.github/workflows/release.yaml'
    with:
      tag: ${{ matrix.version }}
      target: prod
      packages: ${{ matrix.packages }}
    secrets: inherit
