name: nginx

on:
  schedule:
    - cron: "00 01 * * 1"
  push:
    branches:
      - 'main'
    paths:
      - 'images/nginx/*.yaml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write
  actions: read

jobs:
  publish:
    strategy:
      matrix:
        version: [latest, "1.27", "1.26"]
        variant: [prod, shell]
        include:
          - version: latest
            packages: ''
          - version: "1.27"
            packages: 'nginx~1.27,nginx-package-config~1.27,nginx-mod-stream~1.27'
          - version: "1.26"
            packages: 'nginx~1.26,nginx-package-config~1.26,nginx-mod-stream~1.26'
    name: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || '' }}
    uses: './.github/workflows/release.yaml'
    with:
      tag: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || '' }}
      target: ${{ matrix.variant }}
      packages: ${{ matrix.packages }}
    secrets: inherit
