name: nginx

on:
  schedule:
    - cron: "00 01 * * 1"
  pull_request:
    paths:
      - .github/workflows/nginx.yaml
      - 'images/nginx/*.yaml'
      - 'images/nginx/**/*.yaml'
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/nginx.yaml
      - 'images/nginx/*.yaml'
      - 'images/nginx/**/*.yaml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write
  actions: read

jobs:
  publish:
    strategy:
      matrix:
        version: [latest, "1.29", "1.28", "1.27"]
        variant: [prod, shell]
    name: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || '' }}
    uses: './.github/workflows/release.yaml'
    with:
      tag: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || '' }}
      target: ${{ matrix.variant }}
      packages: >-
        ${{ matrix.version != 'latest' && format('nginx~{0},nginx-package-config~{0},nginx-mod-stream~{0}', matrix.version) || '' }}
    secrets: inherit
