name: openvpn

on:
  schedule:
    - cron: "00 01 * * 1-5"
  pull_request:
    paths:
      - .github/workflows/openvpn.yaml
      - 'images/openvpn/*.yaml'
      - 'images/openvpn/**/*.yaml'
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/openvpn.yaml
      - 'images/openvpn/*.yaml'
      - 'images/openvpn/**/*.yaml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write
  actions: read

jobs:
  publish:
    strategy:
      matrix:
        version: [latest]
        variant: [prod, shell]
        include:
          - version: latest
            packages: ''
    name: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || '' }}
    uses: './.github/workflows/release.yaml'
    with:
      tag: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || '' }}
      target: ${{ matrix.variant }}
      packages: ${{ matrix.packages }}
    secrets: inherit
