name: prometheus-adapter

on:
  schedule:
    - cron: "00 01 * * 1-5"
  push:
    branches:
      - 'main'
    paths:
      - 'images/prometheus-adapter/*.yaml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write
  actions: read

jobs:
  publish:
    strategy:
      matrix:
        version: [latest, "0.12"]
        variant: [prod, shell]
        include:
          - version: latest
            packages: ''
          - version: "0.12"
            packages: 'prometheus-adapter~0.12'
    name: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || '' }}
    uses: './.github/workflows/release.yaml'
    with:
      tag: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || '' }}
      target: ${{ matrix.variant }}
      packages: ${{ matrix.packages }}
    secrets: inherit
