name: socat

on:
  schedule:
    - cron: "00 01 * * 1"
  pull_request:
    paths:
      - .github/workflows/socat.yaml
      - 'images/socat/**.yaml'
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/socat.yaml
      - 'images/socat/**.yaml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write
  actions: read

jobs:
  publish:
    strategy:
      matrix:
        version: [latest]
        variant: [prod, shell]
    name: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || '' }}
    uses: './.github/workflows/release.yaml'
    with:
      tag: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || '' }}
      target: ${{ matrix.variant }}
    secrets: inherit
