name: traefik

on:
  schedule:
    - cron: "00 01 * * 1-5"
  pull_request:
    paths:
      - .github/workflows/traefik.yaml
      - 'images/traefik/*.yaml'
      - 'images/traefik/**/*.yaml'
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/traefik.yaml
      - 'images/traefik/*.yaml'
      - 'images/traefik/**/*.yaml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write
  actions: read

jobs:
  publish:
    strategy:
      matrix:
        version: [latest, "3.3"]
        variant: [prod, shell]
    name: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || '' }}
    uses: './.github/workflows/release.yaml'
    with:
      tag: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || '' }}
      target: ${{ matrix.variant }}
      packages: >-
        ${{ matrix.version != 'latest' && format('traefik~{0}', matrix.version) || '' }}
    secrets: inherit
